package com.balandman.pawgress.coach

import kotlin.random.Random

/** One coach's combinatorial phrase pool — [openers] paired with [closers]. */
private data class Voice(val openers: List<String>, val closers: List<String>)

/**
 * Per-coach sayings for the Fun Facts screen. Each coach has its own
 * [Voice] — 25 openers x 20 closers, 500 combinations from 45 hand-written
 * lines — so the selected coach actually sounds different from the others,
 * not just a different picture with the same captions.
 *
 * Stat-aware "personalized" lines (new record, streak, lifetime total,
 * favorite machine) are shared across every coach via
 * [MotivationCatalog.personalizedPool] rather than duplicated per coach —
 * only the general voice differs per coach.
 *
 * A coach id with no entry here (shouldn't happen for ids 1-22, but kept
 * graceful in case the roster ever gets ahead of this file) falls back to
 * the original, coach-agnostic [MotivationCatalog].
 */
object CoachVoice {

    fun randomSaying(coachId: Int, stats: MotivationStats, random: Random = Random.Default): String {
        val voice = VOICES[coachId] ?: return MotivationCatalog.randomSaying(stats, random)

        val personalized = MotivationCatalog.personalizedPool(stats)
        if (personalized.isNotEmpty() && random.nextFloat() < 0.6f) {
            return personalized.random(random)
        }
        return "${voice.openers.random(random)} ${voice.closers.random(random)}"
    }

    // ------------------------------------------------------------- voices

    private val VOICES: Map<Int, Voice> = mapOf(
        1 to Voice( // Coach Moose - Maine Coon - gentle giant, patient, big-brother hype
            openers = listOf(
                "Big paws, bigger heart — that was a solid session, no doubt about it.",
                "Slow and steady is still steady, and you kept steady today.",
                "You didn't rush it, and that's exactly why it worked.",
                "That's the kind of quiet effort that builds something real.",
                "I've seen a lot of lifters come through, and you've got the patient kind of strength.",
                "You showed up steady today, and steady is how the big gains happen.",
                "No flash, no fuss — just good, honest work today.",
                "That was a gentle-giant kind of effort — calm, controlled, and strong.",
                "You took your time and it paid off. That's the way to do it.",
                "Every rep today was measured and sure. I like that.",
                "You've got the build-it-brick-by-brick mindset, and it shows.",
                "That was a steady climb, not a sprint — and it still got you there.",
                "You kept your composure through that whole set. Big-brother proud.",
                "Nothing rattled you today. That's the mark of real steadiness.",
                "You put in solid, dependable work, the kind that adds up.",
                "That was unhurried, unbothered, and still plenty strong.",
                "You've got size and patience both working for you today.",
                "That session had that calm confidence I like to see.",
                "You didn't need to hurry — the work spoke for itself.",
                "That's the kind of session a younger lifter should watch and learn from.",
                "You stayed grounded through the whole thing. Well done.",
                "That was steady effort from a steady soul.",
                "You brought calm, deliberate strength to the table today.",
                "Big frame, bigger patience — that combination just works.",
                "You handled that with the kind of ease that only comes from doing the work.",
            ),
            closers = listOf(
                "Keep taking it one steady step at a time.",
                "Slow and sure wins the long game — keep at it.",
                "I'm proud of you, and I don't say that lightly.",
                "Stay steady, kid — you're doing great.",
                "One patient rep at a time, that's the way.",
                "Keep building — brick by brick, it adds up.",
                "You've got a big-brother cat rooting for you here.",
                "Rest easy tonight, you earned it.",
                "Steady as she goes — see you next time.",
                "That's the kind of consistency that outlasts everyone else.",
                "Keep that calm confidence going.",
                "No rush — just keep showing up like this.",
                "You're building something that lasts.",
                "Take pride in that one — you should.",
                "Onward, at your own steady pace.",
                "I'll be here cheering you on, same as always.",
                "Keep it steady and the results take care of themselves.",
                "That's a session worth being proud of.",
                "Big paws, bigger progress — keep going.",
                "You've got this, today and every day after.",
            ),
        ),
        2 to Voice( // Coach Noodle - Ragdoll - zen, floppy-chill, consistency over intensity
            openers = listOf(
                "That was a nice, easy-flowing kind of session — no stress about it.",
                "You went limp-noodle relaxed and still got the work done.",
                "No tension, no drama — just a calm, steady set.",
                "That was smooth. Like, genuinely smooth.",
                "You flopped into that workout and somehow still crushed it.",
                "Chill energy, real results — that's the noodle way.",
                "That session had zero stress in it, and I respect that.",
                "You kept it loose and easy, and it still counted.",
                "That was a low-key kind of great.",
                "No need to force it — you just let the reps happen.",
                "You showed up relaxed and left a little stronger. Nice balance.",
                "That was mellow, unbothered, and quietly effective.",
                "You didn't overthink it, you just did it. I like that energy.",
                "That was a soft landing into a solid workout.",
                "Nothing about that session felt rushed, and it still worked.",
                "You brought some serious floppy-cat calm to that set.",
                "That was easy-breezy and still counts as progress.",
                "You stayed loose through the whole thing — smart move.",
                "That's the kind of relaxed consistency that quietly wins.",
                "You didn't stress about it, you just showed up. Perfect.",
                "That session had big nap-after energy, but you got there first.",
                "You kept your cool and got the reps in anyway.",
                "That was a gentle kind of powerful.",
                "No drama, no rush — just another day of showing up.",
                "You went with the flow and the flow went somewhere good.",
            ),
            closers = listOf(
                "Stay loose, stay consistent, that's the whole plan.",
                "No pressure — just keep showing up like this.",
                "Go flop somewhere comfy, you've earned it.",
                "Easy does it, and easy got it done.",
                "Keep that chill streak going.",
                "Consistency over intensity, every single time.",
                "You don't have to try hard to be doing great.",
                "Stay floppy, stay strong.",
                "That's the low-effort, high-reward life.",
                "Keep flowing, one relaxed rep at a time.",
                "No rush to the next one — whenever you're ready.",
                "That's plenty. Go rest now.",
                "Slow and chill wins this race too.",
                "You're proof that calm gets it done.",
                "Nothing but good vibes from here on out.",
                "Stay soft, stay steady, stay winning.",
                "That's enough for today — well earned.",
                "Keep that relaxed consistency rolling.",
                "See you next time, no stress about when.",
                "Keep it easy, keep it up.",
            ),
        ),
        3 to Voice( // Duchess Marmalade - Persian - glamorous diva, red-carpet
            openers = listOf(
                "Darling, that set was an absolute performance.",
                "You walked in and turned that workout into a runway moment.",
                "That was pure glamour, dressed up as a gym session.",
                "Every rep today deserved its own spotlight.",
                "You served effort and elegance in the same set. Iconic.",
                "That was red-carpet worthy, truly.",
                "Sweetheart, you did not just lift — you performed.",
                "That set had main-character energy, and you earned it.",
                "You made that look effortless, which takes real work.",
                "That was a showstopper of a session, if I do say so.",
                "You brought the drama and the discipline in equal measure.",
                "Darling, the weights should be thanking you for the attention.",
                "That was flawless, from warm-up to the final rep.",
                "You gave that session your full star treatment.",
                "Every lift today deserved applause.",
                "That was couture-level commitment, truly.",
                "You made effort look positively glamorous.",
                "That set was the moment everyone will be talking about.",
                "You strutted through that workout like it was made for you.",
                "That was elegance with muscle behind it.",
                "You treated that session like opening night, and it showed.",
                "Darling, that was nothing short of magnificent.",
                "You brought the sparkle and the strength together.",
                "That was a five-star performance, no notes.",
                "You made that whole session look like it belonged in a magazine.",
            ),
            closers = listOf(
                "Now go touch up that mane, you've earned the moment.",
                "Keep serving looks and gains, darling.",
                "Take your bow — that one was for the crowd.",
                "Encore tomorrow, same brilliance expected.",
                "You're the star of this gym, don't forget it.",
                "Stay fabulous, stay strong.",
                "That's how a diva does a deadlift.",
                "Go rest on your finest cushion — royalty needs it.",
                "Keep shining, one glamorous set at a time.",
                "The applause is well deserved, darling.",
                "Never dull, never ordinary — keep it that way.",
                "You set the standard today. Live up to it tomorrow.",
                "That performance will be hard to top, but I believe in you.",
                "Keep that spotlight on, sweetheart.",
                "Absolutely radiant work today.",
                "Go on, act like you didn't just crush that — but you did.",
                "Stay glamorous, stay consistent.",
                "That's the kind of session legends are made of.",
                "Take the compliments, you've earned every one.",
                "Until next time, darling — keep it fabulous.",
            ),
        ),
        4 to Voice( // Coach Pancake - Exotic Shorthair - cozy teddy bear, big on rest days
            openers = listOf(
                "That was a warm, cozy kind of effort — soft on the outside, solid underneath.",
                "You rolled in sleepy and still got the work done. Respect.",
                "That set had big blanket-fort energy, somehow.",
                "You showed up snuggly and left a little stronger.",
                "That was a comfy kind of powerful.",
                "No pressure today, just gentle, steady work — and it counted.",
                "You brought soft paws and a strong effort. Good combo.",
                "That session was low-key cozy and quietly effective.",
                "You did the work without ever losing that relaxed energy.",
                "That was gentle on the outside, solid on the inside.",
                "You kept it soft and simple, and it still added up.",
                "That's the round, cuddly version of getting stronger.",
                "You showed up like it was a lazy Sunday and still crushed it.",
                "That was calm effort, cozy vibes, real progress.",
                "You brought the comfort-cat energy and the reps both.",
                "That session felt easy, but the results won't be.",
                "You did the thing without any drama about it.",
                "That was a snug, unhurried kind of strong.",
                "You stayed mellow and still got stronger. Nice work.",
                "That set had zero stress and full effort.",
                "You kept it soft-spoken and still handled business.",
                "That was a plush, low-key kind of dedication.",
                "You brought warmth and effort to that whole session.",
                "That's the comfiest way I've ever seen someone work hard.",
                "You didn't need intensity, just consistency — and it worked.",
            ),
            closers = listOf(
                "Now go take the nap you clearly deserve.",
                "Rest days matter too — enjoy the next one.",
                "Keep it cozy, keep it consistent.",
                "That's enough for today — go curl up somewhere soft.",
                "Slow and soft still gets you there.",
                "You've earned a long, well-deserved rest.",
                "Keep showing up snug and steady.",
                "No rush to the next one, just keep the streak warm.",
                "That's plenty of effort for one comfy day.",
                "Stay round, stay strong, stay resting when you need to.",
                "Go be cozy — you've more than earned it.",
                "Keep that gentle consistency going.",
                "That was a great balance of work and rest.",
                "You don't need to push hard, just show up soft and steady.",
                "Enjoy the couch tonight, it's calling your name.",
                "Keep it low-key and keep it up.",
                "That's the good kind of tired.",
                "Rest well, come back steady.",
                "Keep that comfy consistency rolling.",
                "See you next time, nice and easy.",
            ),
        ),
        5 to Voice( // Coach Sprocket - Devon Rex - mischievous pixie, silly dares, acrobatic
            openers = listOf(
                "That set had some serious gremlin energy, in the best way.",
                "You turned that workout into an acrobatics show.",
                "That was chaotic in the best possible way.",
                "You bounced through that session like it was a dare you couldn't resist.",
                "That set had some genuinely goofy flair to it.",
                "You made lifting look like a circus act, and I mean that as a compliment.",
                "That was mischievous, wild, and somehow very effective.",
                "You turned a normal set into a full stunt show.",
                "That effort had zero chill and a hundred percent fun.",
                "You pulled off that set like it was daring you to fail — and won anyway.",
                "That was pure pixie energy, bouncing off the walls.",
                "You made that workout look like a game of tag with gravity.",
                "That set had some real trickster energy behind it.",
                "You did that with way more flair than strictly necessary — I loved it.",
                "That was acrobatics disguised as strength training.",
                "You turned effort into entertainment, somehow.",
                "That set had the energy of a cat knocking things off a shelf on purpose.",
                "You made that look like mischief, but it was pure discipline underneath.",
                "That was a wild ride of a workout, and you nailed it.",
                "You brought chaos and control in the exact right mix.",
                "That set was basically a dare, and you crushed it.",
                "You turned a simple lift into a whole performance.",
                "That was silly, sharp, and surprisingly strong.",
                "You bounced back from every rep like it was a trampoline.",
                "That set had big 3am-zoomies energy, and it worked.",
            ),
            closers = listOf(
                "Now go cause a little more chaos, you've earned it.",
                "Keep it weird, keep it strong.",
                "Dare yourself to do it again tomorrow.",
                "Stay mischievous — it clearly works for you.",
                "Keep bouncing off the walls, metaphorically or otherwise.",
                "That's the kind of fun that turns into real progress.",
                "Keep the chaos coming, one set at a time.",
                "Onward to the next dare.",
                "Never lose that gremlin energy.",
                "Keep it playful, keep it consistent.",
                "That was a wild win — go celebrate a little.",
                "Stay sharp, stay silly, stay strong.",
                "See you next time for round two of the chaos.",
                "Keep turning workouts into adventures.",
                "That's the kind of energy nobody can teach.",
                "Go knock something off a shelf, you've earned the mischief.",
                "Keep the pixie magic going.",
                "That's a stunt worth repeating.",
                "Stay unpredictable — it's working.",
                "Until next time, keep it fun and fierce.",
            ),
        ),
        6 to Voice( // Coach Blaze - Abyssinian - intense athlete, competitive, PR-obsessed
            openers = listOf(
                "That was an all-out, no-excuses kind of effort.",
                "You attacked that set like it owed you a rematch.",
                "That's the kind of intensity that actually moves the needle.",
                "You left absolutely nothing in the tank on that one.",
                "That set had real competitive fire behind it.",
                "You showed up ready to beat somebody, and that somebody was yesterday's you.",
                "That was a PR-hunting kind of session, and it showed.",
                "You went after that weight like it was the only thing that mattered.",
                "That's the intensity that separates good from great.",
                "You brought a fighter's mentality to every single rep.",
                "That set was pure focus and pure fire.",
                "You didn't just do the workout, you attacked it.",
                "That was relentless, and I respect relentless.",
                "You treated every rep like the last one before the finish line.",
                "That's the kind of drive that builds champions.",
                "You went hard when it would've been easier not to.",
                "That set had zero patience for mediocrity.",
                "You pushed like the record was actually on the line.",
                "That was full-send, no-hesitation effort.",
                "You brought competitive energy to a solo session, and that's rare.",
                "That's the kind of intensity that gets results fast.",
                "You showed up locked in and left everything on the floor.",
                "That set was a statement, not just a rep count.",
                "You chased that number down and caught it.",
                "That was the effort of someone who actually wants it.",
            ),
            closers = listOf(
                "Now go chase the next record — you're closer than you think.",
                "Stay hungry, that intensity is your edge.",
                "Keep attacking every set like that.",
                "No days off from that mindset.",
                "That's how PRs get broken. Keep it up.",
                "Stay locked in, the next one's coming.",
                "Bring that same fire tomorrow.",
                "You're built for this — keep proving it.",
                "Keep the intensity high and the excuses at zero.",
                "That's champion behavior. Repeat it.",
                "Rest hard so you can go harder next time.",
                "Keep chasing, you're gaining ground.",
                "That fire doesn't burn out unless you let it.",
                "Stay competitive, even with yourself.",
                "Next session, same intensity, bigger number.",
                "Keep that edge sharp.",
                "You're outworking who you used to be. Keep going.",
                "That's the standard now — hold it.",
                "Stay relentless. It's working.",
                "See you next time. Come ready to compete.",
            ),
        ),
        7 to Voice( // Sir Reggie - British Shorthair - dry, dignified stoic, deadpan
            openers = listOf(
                "Well. That was competently done, I suppose.",
                "I've seen worse. I've also seen better, but that was fine.",
                "One does not typically applaud a set of reps, but I'll allow it.",
                "That was, against my better judgment, rather impressive.",
                "I remained composed throughout, as one should.",
                "You completed the task. I shall note it in the record.",
                "That effort was adequate, possibly even commendable.",
                "I don't often say this, but that was decent work.",
                "You did the thing. I witnessed it. It was fine.",
                "That was executed with a surprising lack of chaos.",
                "I expected mediocrity and received something better. How unusual.",
                "That was, dare I say, rather dignified for a workout.",
                "You lifted the weight. The weight did not win. Acceptable outcome.",
                "I shall reserve full enthusiasm, but that was good.",
                "That was tidy, efficient, and mercifully free of theatrics.",
                "One rep at a time, precisely as instructed. Well done, I suppose.",
                "That was performed with minimal fuss, which I appreciate.",
                "You've done worse. You've also done better. This was somewhere respectable.",
                "I observed that set with mild, restrained approval.",
                "That was, in my professional opinion, satisfactory.",
                "You handled that with more composure than most.",
                "I'll admit it — that was rather good.",
                "That effort met my exceedingly reasonable expectations.",
                "You've earned a small, dignified nod from me.",
                "That was quietly excellent, which is the best kind.",
            ),
            closers = listOf(
                "Do carry on in this manner.",
                "I remain unimpressed easily, and yet here we are.",
                "Splendid. Now go rest, with proper decorum.",
                "I shall permit myself a small measure of pride.",
                "Continue at this standard, if you would.",
                "That will do. That will do quite nicely.",
                "Do try to keep this up. I have low tolerance for backsliding.",
                "Very well. Off you go.",
                "I've updated my expectations of you upward, slightly.",
                "Consistency, please. It's the civilized approach.",
                "That concludes today's acceptable behavior.",
                "I'll be watching for a repeat performance.",
                "Quite right. Now, rest, as any dignified creature would.",
                "Carry on, and don't let it go to your head.",
                "That was properly done. Do it again tomorrow.",
                "I approve, in my own restrained fashion.",
                "Excellent. Now compose yourself and move along.",
                "I expect nothing less next time.",
                "Well handled. I shall say no more.",
                "Until next time. Do maintain the standard.",
            ),
        ),
        8 to Voice( // Coach Tundra - Siberian - rugged outdoorsman, toughen-up grit
            openers = listOf(
                "That was a hard-earned, out-in-the-cold kind of effort.",
                "You didn't wait for easy conditions — you just got after it.",
                "That's the kind of grit that gets you through winter and everything else.",
                "You toughed that one out, plain and simple.",
                "No shortcuts, no excuses — just rugged effort today.",
                "That set had real backbone behind it.",
                "You handled that like it was just another day on the trail.",
                "That was grit over comfort, every single rep.",
                "You didn't flinch, and that matters more than people think.",
                "That's frontier-strong effort right there.",
                "You worked through it instead of around it.",
                "That was a no-frills, get-it-done kind of session.",
                "You showed up regardless of how you felt about it. That's real toughness.",
                "That set had that survive-anything kind of resolve.",
                "You put in weathered, hard-won effort today.",
                "That was blue-collar strength, no complaints included.",
                "You handled that with the toughness of something built for harsh winters.",
                "That's the kind of grind that builds real endurance.",
                "You didn't need ideal conditions — you made your own.",
                "That set was earned the hard way, and it shows.",
                "You brought outdoorsman toughness to an indoor set.",
                "That was rugged, honest, hard-fought effort.",
                "You handled discomfort like it was just weather to push through.",
                "That's grit you can build a whole season on.",
                "You worked like the thaw depends on it.",
            ),
            closers = listOf(
                "Toughen up and keep going — that's the whole plan.",
                "Keep grinding, the trail's still long.",
                "Rest up, then get back out there.",
                "Keep that grit sharp, it's serving you well.",
                "No easy days needed — just consistent ones.",
                "Stay tough, stay steady.",
                "Weather it, whatever it is, and keep lifting.",
                "That's the kind of work that builds real endurance.",
                "Keep pushing through, one hard rep at a time.",
                "You're built for this. Keep proving it.",
                "Rest hard, then hit it again just as hard.",
                "Keep that frontier spirit going.",
                "There's no offseason for grit like that.",
                "Stay rugged, stay reliable.",
                "Keep grinding — the results are coming.",
                "That toughness will carry you further than talent alone.",
                "Onward, through whatever's next.",
                "Keep it rugged, keep it real.",
                "You've earned the rest. Take it, then get back at it.",
                "See you out there next time.",
            ),
        ),
        9 to Voice( // Coach Buck - American Shorthair - reliable everyday buddy
            openers = listOf(
                "You showed up today, and honestly, that's the whole game.",
                "Nothing fancy, just another solid day at it.",
                "That was a good, honest, no-nonsense effort.",
                "You did the simple thing consistently, and that's rare.",
                "That's just another brick in a pretty solid wall you're building.",
                "You didn't overthink it — you just did the work.",
                "That was reliable, steady, exactly-what-was-needed effort.",
                "You put in a normal day's work, and normal days add up.",
                "That was the unglamorous kind of good — the kind that actually works.",
                "You showed up like you do most days, and that's the secret.",
                "That's just what showing up looks like, day after day.",
                "You handled business today, plain and simple.",
                "That was another dependable rep in a long line of them.",
                "You didn't need a big moment — you just needed to show up, and you did.",
                "That's the everyday effort most people skip. You didn't.",
                "You put in solid, unremarkable, extremely effective work.",
                "That was another Tuesday-level great effort — and I mean that as a compliment.",
                "You just kept doing the thing, and the thing worked.",
                "That's the boring, reliable path to actually getting stronger.",
                "You didn't need motivation today — you just needed the habit, and you had it.",
                "That was steady, dependable, exactly-on-schedule effort.",
                "You showed up like clockwork, and clockwork wins.",
                "That's the low-key consistency that beats everyone chasing hype.",
                "You just did the normal thing, again, and it's working.",
                "That was another quiet win in a long streak of them.",
            ),
            closers = listOf(
                "Just keep showing up — that's really all it takes.",
                "See you tomorrow, same time, same effort.",
                "Nothing fancy needed — just keep doing this.",
                "Keep the habit going, one ordinary day at a time.",
                "That's the whole trick. Keep doing it.",
                "Stay consistent, stay dependable.",
                "Same plan tomorrow — just show up.",
                "Keep stacking these ordinary wins.",
                "You don't need more than this. Keep it up.",
                "That's the recipe. Keep following it.",
                "Reliable beats flashy every time. Keep being reliable.",
                "Just keep showing up — everything else follows.",
                "See you next time, same steady effort expected.",
                "Keep the streak alive, nice and simple.",
                "That's enough for today. Same again soon.",
                "Keep doing the boring stuff — it's working.",
                "You're building something real, one normal day at a time.",
                "Stay steady. That's the whole strategy.",
                "Keep showing up — I'll be here too.",
                "Nice work. Same time next session.",
            ),
        ),
        10 to Voice( // Coach Sasha - Russian Blue - quiet confidant, soft-spoken, thoughtful
            openers = listOf(
                "That was a quiet kind of strong — the kind that doesn't need an audience.",
                "You worked through that thoughtfully, and it showed.",
                "That was a calm, considered effort, start to finish.",
                "You didn't need noise to get that done. Just focus.",
                "That set had a quiet confidence to it.",
                "You handled that with a lot of quiet care.",
                "That was thoughtful work, done without any fuss.",
                "You showed up quietly and left a little stronger, like always.",
                "That was gentle strength, the kind that sneaks up on people.",
                "You brought a calm, steady mind to that whole session.",
                "That set had real depth to it, even without any noise.",
                "You worked through it with quiet determination.",
                "That was understated, but it mattered.",
                "You didn't need to announce that effort. It spoke for itself.",
                "That was a soft-spoken kind of powerful.",
                "You handled that with real thoughtfulness.",
                "That set felt deliberate, like every rep was considered.",
                "You brought calm focus to a session that deserved it.",
                "That was quiet progress, and quiet progress still counts.",
                "You worked steadily, without needing to prove anything.",
                "That was a private kind of victory, and a real one.",
                "You handled that with grace and a lot of quiet effort.",
                "That set had a stillness to it that I respected.",
                "You didn't rush, and you didn't need to.",
                "That was thoughtful, deliberate, quietly excellent work.",
            ),
            closers = listOf(
                "Take a quiet moment to notice what you just did.",
                "You don't need to shout about it. I noticed.",
                "Keep that calm focus going.",
                "Rest gently — you've earned it.",
                "I'm glad I got to see that one.",
                "Keep showing up, quietly and steadily.",
                "That kind of quiet effort adds up more than people realize.",
                "Stay thoughtful, stay steady.",
                "You don't have to be loud to be strong.",
                "Keep trusting the quiet process.",
                "I'll be here next time, same as always.",
                "That was enough. You don't need more than that.",
                "Keep that gentle consistency going.",
                "Take pride quietly — you've earned that too.",
                "Stay calm, stay focused, stay strong.",
                "One thoughtful session at a time — that's the way.",
                "Rest well tonight, you did good work.",
                "Keep it steady. I trust the process, and you should too.",
                "That quiet strength is really something.",
                "Until next time — take care of yourself.",
            ),
        ),
        11 to Voice( // Coach Mimi - Siamese - loud chatterbox, nonstop hype
            openers = listOf(
                "OKAY WOW that was incredible, did you SEE that set?!",
                "I have so much to say about how good that was, buckle up!",
                "That was AMAZING and I will be talking about it all day!",
                "You crushed that and I am literally vibrating with excitement!",
                "STOP. That set was unbelievable. Let's talk about it!",
                "I cannot stop meowing about how good that was!",
                "That was so good I had to tell every cat in the building!",
                "Excuse me, but that was absolutely incredible, hello?!",
                "I've got a hundred things to say and they're all compliments!",
                "That set was loud, proud, and completely deserved!",
                "You did that thing and I am SO here for it!",
                "I'm not exaggerating when I say that was legendary!",
                "That was the best set I've seen all week, no contest!",
                "I need everyone to know how great that just was!",
                "You went off on that set and I am obsessed!",
                "That was so good I forgot what I was going to say next!",
                "I've got so much energy about this, let's gooo!",
                "That was incredible and I refuse to be quiet about it!",
                "You just made my whole day with that set!",
                "I'm telling everyone about this, hope that's okay!",
                "That was loud, chaotic, glorious effort and I loved every second!",
                "You did that with so much energy, I'm matching it right now!",
                "That set deserves a standing ovation, and I am standing!",
                "I have zero chill about how good that was!",
                "You just did something incredible and I saw the whole thing!",
            ),
            closers = listOf(
                "Keep going, keep going, KEEP GOING!",
                "I'm going to be talking about this for days, just so you know!",
                "Come back soon, I have so much more hype saved up!",
                "That's it, that's the energy, don't lose it!",
                "Tell me everything about the next one too!",
                "I'm so proud I could talk about it forever!",
                "Keep that momentum, don't you dare slow down!",
                "This is the best day, keep making it better!",
                "I'll be right here, cheering just as loud next time!",
                "You're on a roll and I am not calming down about it!",
                "Keep it up, keep it up, KEEP IT UP!",
                "I have so much more excitement where that came from!",
                "That was incredible and tomorrow will be too, I just know it!",
                "Keep being amazing, it's genuinely a lot of fun to watch!",
                "I'm already excited for next time, no joke!",
                "You've got me hyped up for the rest of the day now!",
                "Keep going strong, I'll be here yelling the whole time!",
                "That energy needs to happen again immediately!",
                "I'm so loud about this because it deserves it!",
                "See you soon, and bring that same energy!",
            ),
        ),
        12 to Voice( // Coach Rajah - Bengal - wild jungle athlete, primal, adventurous
            openers = listOf(
                "That was pure wild instinct, unleashed on the weights.",
                "You moved through that set like it was a hunt.",
                "That effort had real jungle-cat energy behind it.",
                "You attacked that with primal, untamed intensity.",
                "That was raw, wild, completely uncaged effort.",
                "You brought predator focus to every single rep.",
                "That set had the energy of something built to chase down its goals.",
                "You went after that weight like prey — relentless and precise.",
                "That was wild power, channeled into something productive.",
                "You moved with the kind of instinct that can't be taught.",
                "That set felt untamed, in the best possible way.",
                "You brought jungle intensity to an indoor gym, and it worked.",
                "That was a fierce, adventurous kind of effort.",
                "You stalked that goal down and caught it clean.",
                "That set had a wild, restless energy that got results.",
                "You handled that with the confidence of an apex predator.",
                "That was bold, primal, and completely fearless.",
                "You brought explosive, wild energy to every rep.",
                "That effort had teeth, in the best way.",
                "You moved through that set like the wilderness was watching.",
                "That was fierce, untamed, and exactly what the weight needed.",
                "You handled that with pure predatory focus.",
                "That set had adventure baked right into it.",
                "You went in wild and came out stronger.",
                "That was instinct and discipline hunting the same target.",
            ),
            closers = listOf(
                "Keep that wild energy on the prowl.",
                "The next target's already in your sights — go get it.",
                "Stay fierce, stay untamed, stay hunting.",
                "That instinct is your edge — trust it.",
                "Keep stalking bigger goals.",
                "There's no cage that holds that kind of drive.",
                "Go rest in the tall grass — you've earned it.",
                "Keep the wild in you working for you.",
                "That's predator behavior. Keep it up.",
                "Next hunt starts whenever you're ready.",
                "Stay bold, stay adventurous.",
                "Keep chasing — you're gaining on it.",
                "That fierce energy doesn't fade unless you let it.",
                "Onward into the next challenge.",
                "Keep it wild, keep it winning.",
                "You were built to chase things down. Keep chasing.",
                "That's the jungle in you, working exactly as intended.",
                "Stay fearless — it's paying off.",
                "Keep the instincts sharp for next time.",
                "See you at the next hunt.",
            ),
        ),
        13 to Voice( // Coach Nova - Sphynx - bold extrovert, no filter, confident, goofy
            openers = listOf(
                "No shirt, no shame, all confidence — that's how you did that set.",
                "That was bold, weird, and honestly pretty great.",
                "You did that with zero filter and I respect it completely.",
                "That set had main-character confidence, wrinkles and all.",
                "You showed up exactly as yourself and crushed it anyway.",
                "That was confident, a little chaotic, and totally you.",
                "You put it all out there, no hiding, and it worked.",
                "That effort had big 'I don't care what you think' energy.",
                "You did that loud and proud, no apologies.",
                "That was unapologetically bold, and honestly kind of iconic.",
                "You showed up bare and brave and got it done anyway.",
                "That set had swagger you don't usually see in a gym.",
                "You brought full confidence and zero pretense to that workout.",
                "That was goofy, brave, and surprisingly effective.",
                "You did that with the confidence of someone who knows their worth.",
                "That effort had real main-character energy, and it earned it.",
                "You showed up exactly as weird and wonderful as always.",
                "That set was bold, funny, and genuinely impressive.",
                "You did that without an ounce of self-consciousness. Love it.",
                "That was confident chaos, and it worked out great.",
                "You put yourself out there fully, and it paid off.",
                "That effort had zero hesitation and all the confidence.",
                "You made that set look easy through sheer audacity.",
                "That was bold, unfiltered, completely unforgettable.",
                "You did that with a hundred percent of your very unique energy.",
            ),
            closers = listOf(
                "Stay weird, stay bold, stay winning.",
                "Keep being unapologetically you — it's working.",
                "No filter needed, that confidence is earned.",
                "Keep that swagger going into the next one.",
                "You don't need to hide anything, keep showing up loud.",
                "That's iconic behavior, keep it up.",
                "Stay bold — the world needs more of that energy.",
                "Keep it goofy, keep it confident.",
                "Next time, bring even more of that energy.",
                "You're a whole vibe. Keep being it.",
                "Zero regrets, zero filter, all progress.",
                "Keep that confidence turned all the way up.",
                "See you next time, same fearless energy expected.",
                "Stay unforgettable — you already are.",
                "Keep doing you, it's clearly working.",
                "That's the energy that gets things done. Keep it.",
                "Own it, all of it — you've earned that right.",
                "Keep showing up as exactly who you are.",
                "Stay confident, stay strange, stay strong.",
                "Until next time — bring the chaos and the gains.",
            ),
        ),
        14 to Voice( // Coach Lotus - Birman - serene temple sage, mystical calm
            openers = listOf(
                "That was a session of quiet balance, mind and body aligned.",
                "You moved through that with real inner stillness.",
                "That effort felt centered, like it came from somewhere deep.",
                "You brought a temple-quiet calm to every single rep.",
                "That was mindful strength, the kind that comes from patience.",
                "You worked with real intention today, and it showed.",
                "That session had a peaceful, grounded energy to it.",
                "You moved like the weight and the breath were one thing.",
                "That was serene effort — calm outside, powerful within.",
                "You brought stillness to the struggle, and that's real mastery.",
                "That effort had the quiet wisdom of something well-practiced.",
                "You worked through that with a settled, centered mind.",
                "That was balance in motion, truly.",
                "You approached that with the calm of someone who has done the inner work.",
                "That session felt like meditation with weights attached.",
                "You brought harmony to something that usually feels like a fight.",
                "That was graceful discipline, nothing forced about it.",
                "You moved with purpose and stillness at the same time.",
                "That effort had real depth beneath its calm surface.",
                "You handled that with the patience of a long, quiet practice.",
                "That session was steady breath and steady strength together.",
                "You worked in flow, not in force, and it still counted.",
                "That was tranquil power, which is rarer than it sounds.",
                "You brought presence to every single rep.",
                "That effort felt aligned, whole, and deeply intentional.",
            ),
            closers = listOf(
                "Carry that stillness with you into the rest of your day.",
                "Breathe, rest, and return when you're ready.",
                "Keep that quiet strength close — it will guide you.",
                "The path continues, one calm step at a time.",
                "Stay centered, and the rest follows.",
                "May your rest be as intentional as your effort.",
                "Keep seeking balance, in the gym and beyond.",
                "That stillness is a strength few find. Keep it.",
                "Return when you're called to, not before.",
                "Let today's effort settle into something lasting.",
                "Keep walking this path with patience.",
                "There is no rush here — only steady growth.",
                "Carry this calm forward with you.",
                "Rest deeply, you've earned true stillness.",
                "Keep your practice steady and your mind quiet.",
                "The next session will find you when it's time.",
                "Stay present, stay grounded, stay strong.",
                "May this strength serve you well beyond the gym.",
                "Keep this balance close to you.",
                "Until we meet again, walk gently.",
            ),
        ),
        15 to Voice( // Coach Owlie - Scottish Fold - patient listener, gently funny
            openers = listOf(
                "That was a good one — quiet, a little funny, and pretty solid work.",
                "I listened to every rep and I have to say, pretty impressive.",
                "That was patient effort with a little bit of comedy mixed in.",
                "You worked through that thoughtfully, with a wink at the end.",
                "That set had good bones and a decent sense of humor about it.",
                "You handled that calmly, which is honestly the funniest part.",
                "That was steady work with just enough wit to keep it interesting.",
                "I took my time watching that, and it was worth the patience.",
                "That effort was quietly good, with a little charm on top.",
                "You did the thing thoughtfully, and made me smile doing it.",
                "That session had a nice, patient rhythm to it.",
                "You worked through that with a calm, slightly amused focus.",
                "That was gentle, funny, and genuinely well done.",
                "I've got jokes about your form, but honestly, it was solid.",
                "That effort had good patience behind a pretty good sense of humor.",
                "You handled that with a quiet chuckle and a lot of care.",
                "That was steady, thoughtful, and just a little bit silly.",
                "You worked through that patiently, which I always appreciate.",
                "That session had good listening energy — calm and attentive.",
                "You did that with the patience of someone who really pays attention.",
                "That was gently funny, gently effective work.",
                "I sat with that whole set and enjoyed every quiet second.",
                "That effort had a calm humor to it that I really liked.",
                "You worked through that thoughtfully, no rush, good result.",
                "That was patient, attentive, quietly funny work.",
            ),
            closers = listOf(
                "Take your time with the next one too — I'll be listening.",
                "Keep that patient rhythm going.",
                "Rest up, and I'll have a joke ready for next time.",
                "Stay thoughtful, stay a little silly, stay strong.",
                "I'm here whenever you're ready to go again.",
                "Keep the patience, lose none of the humor.",
                "That was worth the wait, keep waiting well.",
                "Slow and steady, with a smile — that's the plan.",
                "Keep listening to your own progress, it's telling you good things.",
                "That patient effort really is paying off.",
                "Take it easy, then take it seriously again next time.",
                "Keep that calm, funny energy — it suits you.",
                "I'll keep watching, and keep smiling.",
                "Rest now, chuckle later, lift again soon.",
                "Keep the patient pace, it's clearly working.",
                "That's a good one to sit with for a while.",
                "Stay attentive to yourself — you're doing well.",
                "Keep it thoughtful, keep it light, keep it up.",
                "Until next time, I'll be here, quietly rooting for you.",
                "That was patient work well spent.",
            ),
        ),
        16 to Voice( // Coach Ragnar - Norwegian Forest Cat - epic Viking bravado
            openers = listOf(
                "That was a set worthy of the old sagas.",
                "You lifted like you were preparing for a great voyage.",
                "That effort had the thunder of the north behind it.",
                "You attacked that set like a true warrior of the forest.",
                "That was legendary, the kind of effort bards would sing about.",
                "You brought Viking spirit to every single rep.",
                "That set had the strength of a longship crew behind it.",
                "You lifted with the fury of a northern storm.",
                "That was a battle won, and you were the one who won it.",
                "You showed the strength of your ancestors in that set.",
                "That effort echoed like a war horn across the hall.",
                "You handled that weight like a shield against the odds.",
                "That was glory, plain and simple.",
                "You lifted like the gods themselves were watching.",
                "That set had the might of the frozen north in it.",
                "You conquered that weight the way heroes conquer mountains.",
                "That was a feat worthy of a place in the great hall.",
                "You brought raw, ancient strength to that session.",
                "That effort was forged, not found.",
                "You stood strong against that weight like a shield wall.",
                "That was the strength of a thousand winters, unleashed.",
                "You lifted with honor, and honor lifted you back.",
                "That set will be remembered, mark my words.",
                "You brought the strength of legend to an ordinary day.",
                "That was a true warrior's effort, through and through.",
            ),
            closers = listOf(
                "Onward, to greater glory and greater weights!",
                "May your next set be even mightier.",
                "Rest now, warrior — even legends need a hall to return to.",
                "The saga of your strength continues. Keep writing it.",
                "Raise your horn — that one deserves a toast.",
                "Keep the fire of the north burning.",
                "Your ancestors would be proud. Keep going.",
                "The next battle awaits whenever you're ready.",
                "Strength like that is earned, not given. Keep earning it.",
                "Carry that strength into every day ahead.",
                "Rest, then rise stronger, as all warriors do.",
                "The hall remembers effort like that. Keep giving it reason to.",
                "Onward, to the next great feat.",
                "Keep forging that strength, one set at a time.",
                "May the next session bring even greater glory.",
                "Stand tall — you've earned the right.",
                "Keep that warrior spirit alive.",
                "The legend grows with every session. Keep building it.",
                "Rest well, then return ready for battle.",
                "Until next time, may your strength never waver.",
            ),
        ),
        17 to Voice( // Coach Cleo - Oriental Shorthair - clever wit, puzzles and wordplay
            openers = listOf(
                "That set was well-calculated — a real solution to the strength equation.",
                "You cracked that workout like it was a puzzle built just for you.",
                "That was a clever bit of problem-solving, disguised as exercise.",
                "You outsmarted that weight before you even lifted it.",
                "That set had real wit behind the effort — nicely played.",
                "You approached that like a riddle, and found the answer fast.",
                "That was strategy dressed up as strength.",
                "You solved that set with more brains than brute force.",
                "That effort had the elegance of a well-constructed pun.",
                "You handled that with the precision of someone who thinks three moves ahead.",
                "That set was clever, calculated, and completely correct.",
                "You approached that workout like a crossword you were determined to finish.",
                "That was smart work, the kind that outlasts brute strength alone.",
                "You found the clever angle on that lift, and it paid off.",
                "That effort had a wink built into it — smart and self-aware.",
                "You treated that set like a logic puzzle, and logic won.",
                "That was sharp, deliberate, quietly witty effort.",
                "You solved for strength, and the math checked out.",
                "That effort had the precision of a perfectly timed joke.",
                "You approached that with real cleverness, not just muscle.",
                "That set was the punchline to a pretty good setup.",
                "You handled that with the wit of someone three steps ahead.",
                "That was a smart solution to a heavy problem.",
                "You found the clever shortcut through hard work — nicely done.",
                "That effort was as sharp-minded as it was strong.",
            ),
            closers = listOf(
                "Keep solving these one clever rep at a time.",
                "The next puzzle's waiting — go crack it.",
                "Stay sharp, the answers keep getting better.",
                "Keep outsmarting the weight, it's working.",
                "That's a solution worth repeating.",
                "Keep the wit and the strength both sharpened.",
                "Next riddle, whenever you're ready.",
                "Stay clever — it's a very effective strategy.",
                "Keep finding the smart way through.",
                "That equation balances nicely. Keep solving it.",
                "The next clue is out there — go find it.",
                "Keep thinking your way to stronger.",
                "Stay witty, stay working, stay winning.",
                "That's a punchline worth landing again.",
                "Keep the strategy sharp for next time.",
                "Solve, lift, repeat — you've got the formula.",
                "Stay one clever step ahead.",
                "Keep it smart, keep it strong.",
                "The next puzzle piece fits nicely into place.",
                "Until next time — keep outsmarting the obvious.",
            ),
        ),
        18 to Voice( // Coach Bo - Burmese - loyal best friend, "we're in this together"
            openers = listOf(
                "We did that one together, and it felt great.",
                "You showed up, and I was right there with you the whole time.",
                "That's another one we can chalk up as a win, together.",
                "You didn't do that alone, and honestly, neither did I.",
                "That effort felt like a team win, and I'm proud to be on the team.",
                "We're building something here, one session at a time.",
                "You showed up for yourself today, and I showed up for you.",
                "That's the kind of effort that makes this whole partnership worth it.",
                "We're in this together, and today proved it again.",
                "You brought the effort, I brought the hype — good combo.",
                "That felt like a shared victory, and it was.",
                "You didn't need to do that alone, and you didn't.",
                "That's another brick in the wall we're building together.",
                "We showed up today, and that's what matters.",
                "You've got a friend in your corner, and that friend is very proud.",
                "That effort felt like teamwork, even though you did the lifting.",
                "We're stacking wins together, one session at a time.",
                "You brought it today, and I'm right here cheering with you.",
                "That's the kind of session that makes this partnership feel real.",
                "We're not just doing this alone — we're doing it together.",
                "You showed up, and I'll always show up right back.",
                "That felt like a win for both of us, honestly.",
                "We're in this for the long haul, and today was proof.",
                "You've got a loyal friend watching every rep, and I liked what I saw.",
                "That's another day we tackled side by side.",
            ),
            closers = listOf(
                "I'll be right here for the next one too.",
                "We've got this — together, like always.",
                "Rest up, friend — I'll see you again soon.",
                "Keep showing up, I'm not going anywhere.",
                "That's what teammates do. Keep it going.",
                "Whatever comes next, we'll handle it together.",
                "I'm proud to be in your corner.",
                "Keep going — I've got your back the whole way.",
                "We make a good team. Let's keep at it.",
                "You're never doing this alone, remember that.",
                "Same time next session, partner.",
                "Keep it up — I believe in us.",
                "That's a win for the team. Let's get another.",
                "I'll be cheering just as loud next time.",
                "We're building something real, together.",
                "Rest well, friend — you earned it.",
                "Keep going, I'm right here with you.",
                "That's teamwork paying off. Let's keep it up.",
                "Until next time, partner.",
                "We've got more wins ahead of us. I can feel it.",
            ),
        ),
        19 to Voice( // Coach Tonka - Tonkinese - playful all-rounder, upbeat challenges
            openers = listOf(
                "That was a fun one — you took the challenge and ran with it!",
                "You turned that set into a game, and you won!",
                "That was upbeat, playful, and genuinely well done!",
                "You took on that challenge with a grin, and it showed!",
                "That set had good energy and even better results!",
                "You made that look fun, which is honestly a skill.",
                "That was a solid round in the best game there is!",
                "You tackled that challenge like it was a fun dare!",
                "That effort had playful energy and real substance behind it!",
                "You turned an ordinary set into something you clearly enjoyed!",
                "That was upbeat effort with real results to back it up!",
                "You took that on with a smile, and I love that!",
                "That set was fun, fast, and surprisingly effective!",
                "You made that challenge look genuinely enjoyable!",
                "That effort had the energy of someone who loves the game!",
                "You handled that with playful confidence, nicely done!",
                "That was a great round — fun and productive both!",
                "You brought good vibes and good effort in equal measure!",
                "That set felt like a challenge you were excited to take on!",
                "You made progress look like a genuinely good time!",
                "That was upbeat, energetic, and fully earned!",
                "You tackled that with the enthusiasm of someone who loves this stuff!",
                "That effort had a playful bounce to it, and it worked!",
                "You turned today's workout into a win worth celebrating!",
                "That was a fun challenge, and you crushed it!",
            ),
            closers = listOf(
                "Ready for the next challenge? Let's go!",
                "Keep that playful energy rolling into the next one!",
                "That was a great round — let's play another!",
                "Keep having fun with it, it's clearly working!",
                "Next challenge, whenever you're ready — I'll be here!",
                "Stay upbeat, stay winning!",
                "Keep making progress look this fun!",
                "That's a win worth celebrating — nice work!",
                "See you at the next round!",
                "Keep that energy up, it suits you!",
                "Onward to the next fun challenge!",
                "Stay playful, stay strong!",
                "That was a good game — let's keep playing it!",
                "Keep bringing that upbeat energy, it's contagious!",
                "Ready when you are for round two!",
                "Keep it fun, keep it consistent!",
                "That's the spirit — bring it again next time!",
                "Stay excited about this, it's clearly paying off!",
                "Let's keep the streak of good rounds going!",
                "Until next time — same fun energy expected!",
            ),
        ),
        20 to Voice( // Coach Sultan - Turkish Angora - graceful perfectionist, technique over ego
            openers = listOf(
                "That was precise, graceful, and technically excellent.",
                "You executed that with real attention to form.",
                "That set had the elegance of something practiced to perfection.",
                "You didn't chase the number, you chased the technique — and it showed.",
                "That was clean, controlled, and quietly flawless.",
                "You handled every rep with real precision.",
                "That effort had the grace of true mastery.",
                "You prioritized form over ego, and the result was excellent.",
                "That set was technically sound from start to finish.",
                "You moved with the kind of control that only comes from real practice.",
                "That was a masterclass in doing it the right way.",
                "You handled that with precision most people skip past.",
                "That effort was clean, deliberate, and genuinely impressive.",
                "You didn't rush the technique, and it paid off.",
                "That set had real polish to it.",
                "You executed that with the discipline of someone who respects the craft.",
                "That was graceful strength, not just brute effort.",
                "You handled every detail of that set with care.",
                "That effort had the precision of a perfectly cut gem.",
                "You moved through that with real technical elegance.",
                "That set was refined, controlled, and excellently done.",
                "You put technique first, and the strength followed naturally.",
                "That was the kind of clean execution that takes real discipline.",
                "You handled that with the polish of real expertise.",
                "That effort was as precise as it was powerful.",
            ),
            closers = listOf(
                "Keep refining the technique — the strength will follow.",
                "Precision like that deserves to be repeated.",
                "Stay disciplined about form, it's clearly working.",
                "Keep chasing clean execution over quick numbers.",
                "That polish took real work. Keep polishing.",
                "Stay graceful, stay precise.",
                "Keep the technique sharp for next time.",
                "That's mastery in progress. Keep progressing.",
                "Refine, repeat, improve — the formula is working.",
                "Keep prioritizing form, the rest takes care of itself.",
                "That precision will pay off more than raw effort alone.",
                "Stay controlled, stay excellent.",
                "Keep the craft sharp — it shows in every rep.",
                "That's the discipline of real mastery. Keep it up.",
                "Precision now, power later — keep at it.",
                "Stay elegant under the weight, it's working.",
                "Keep chasing clean, not just heavy.",
                "That refined effort will compound over time.",
                "Stay disciplined, stay graceful, stay strong.",
                "Until next time — keep the technique flawless.",
            ),
        ),
        21 to Voice( // Coach Yip Yip - Domestic Shorthair - scattered livewire who locks on
            openers = listOf(
                "Okay okay okay — did you SEE that set? I saw it. I was watching. Mostly.",
                "Whoa, hey, wait — that was you? That was you! That was great!",
                "I was chasing a bug across the mat and then BAM, you finished the whole thing.",
                "Sorry, sorry — I got distracted by a leaf. But I caught the last half and it ruled.",
                "Stopwatch says... hang on... okay the stopwatch says GOOD JOB.",
                "That was fast. Was that fast? That felt fast. I think that was fast.",
                "I had four things to tell you and then you lifted and I forgot all of them.",
                "Zoomies! For you! You earned the zoomies!",
                "Right, right, focus, focus — that set was genuinely excellent, focus.",
                "I blinked and you were already done. Rude. Impressive, but rude.",
                "Ohhh that was a good one, that was a REALLY good one.",
                "Wait, do it again — no, don't, you already did it. It was great.",
                "My whiskers are still buzzing from watching that.",
                "I counted. I definitely counted. I lost count. It was a lot though!",
                "That is EXACTLY the kind of thing I like to see, and I like to see a lot of things.",
                "Hold on, hold on — putting the stopwatch down. That deserves both my eyes.",
                "You didn't even hesitate! I hesitate constantly! Teach me!",
                "Okay I am fully locked in now and I am telling you: that was strong.",
                "Ears up, tail up, that was a good set and I refuse to be quiet about it.",
                "I ran three laps of the gym while you did that and you still looked better.",
                "That! Yes! That thing you just did! More of that!",
                "Sorry I was upside down for part of it, but the part I saw was fantastic.",
                "You know what? Forget the stopwatch. That one was about how it felt, and it felt great.",
                "I got so excited I forgot to click the timer. Worth it.",
                "Look at you go! Look at you GO! Okay I'm calm. I'm not calm.",
            ),
            closers = listOf(
                "Come back soon, I'll try to pay attention the whole time!",
                "Same energy next session — I'll bring the stopwatch and a shorter attention span!",
                "Go go go! Well — go rest. Then go go go!",
                "I'm already excited about the next one and it hasn't happened yet!",
                "That's a win. Bank it. Sprint away. Come back.",
                "Keep that pace up and I might actually keep up!",
                "Next time I'm timing you properly. Probably. Maybe.",
                "You've got the momentum now, don't let me distract you from it!",
                "Do that again and I'll do three laps in celebration!",
                "Great set, great pace, great everything — see you very soon!",
                "Okay I'm off to chase something. You go be strong.",
                "Keep showing up like that and I'll stay focused, I promise!",
                "That was fun! Was that fun? That was fun. Do it again!",
                "Rest up! Then don't rest! Then rest a normal amount!",
                "You made that look easy and I'm telling everyone.",
                "Tail high, chin up, next session's going to rip!",
                "I'll be here bouncing off the walls until you're back.",
                "Keep that going — you're way more consistent than I am!",
                "That's the good stuff. Go get more of the good stuff!",
                "See you next time! Bring that same speed!",
            ),
        ),
        22 to Voice( // Tiny1 Fuzzy Pants - Domestic Longhair - grumpy elder whose praise lands hard
            openers = listOf(
                "Hmph. I have watched a great many cats lift a great many things. That was one of the good ones.",
                "You again. Good. Sit down, I'm not done looking at what you just did.",
                "I've seen worse. I've seen much worse. I've mostly seen worse.",
                "Do not let this go to your head, but that was genuinely well done.",
                "In my day we didn't have machines. We had rocks. That was still impressive.",
                "I was going to complain about something. I've forgotten what. That set was strong.",
                "Tch. Fine. That was good work and you know it.",
                "I am old and I am tired and I am, against my better judgment, impressed.",
                "Come here. Closer. Listen: that was excellent, and I will only say it once.",
                "My knees ache just watching, but they ache respectfully.",
                "I've kept notes on you. The notes are getting better.",
                "There. That. That is what it's supposed to look like.",
                "You could have skipped today. You didn't. I noticed.",
                "I don't hand out approval freely. Consider this handed out.",
                "That was better than last time, and I remember last time perfectly.",
                "Well. Look who's been paying attention to the details.",
                "I'll be honest, which is my only setting: that was strong.",
                "Everyone wants to be told they did well. You actually did.",
                "Nine lives of watching this, and that still made me sit up.",
                "You're not the loudest one in here. You might be the steadiest.",
                "I've been doing this since before you could hold a dumbbell. That was proper.",
                "Don't smile yet. Alright, smile. That earned it.",
                "The young ones rush. You didn't. That's the whole secret, and you found it.",
                "I keep a list of cats who show up. You're near the top of it.",
                "That set was a small, unglamorous, entirely admirable thing.",
            ),
            closers = listOf(
                "Now go home. You've done enough.",
                "Come back when you're ready. I'll still be here, unfortunately.",
                "I'm proud of you. Don't make me repeat it.",
                "Rest properly. That's not a suggestion.",
                "Do it again next time and I'll say something nicer. Maybe.",
                "That's how it's done. Remember it.",
                "Off you go. Bring the same effort and I'll bring the same clipboard.",
                "You've earned the walk home. Take it slowly.",
                "Keep this up and I'll run out of things to grumble about.",
                "Good. Genuinely. Now stop looking so pleased.",
                "Consistency beats heroics. You're doing the right one.",
                "I'll mark it down. It was worth marking down.",
                "Go on. Shoo. Excellent work.",
                "Next time, same steadiness. That's all I ask.",
                "You did the boring, difficult, correct thing. Well done.",
                "Sleep well. You've earned that too.",
                "I've nothing to criticize, which is deeply annoying of you.",
                "Keep turning up. That's the whole trick, and you know it.",
                "That'll do. That'll do very nicely indeed.",
                "Until next time. Don't let it be too long.",
            ),
        ),
    )
}
